/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gtfs-realtime.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gtfs-realtime.pb-c.h"
void   feed_message__init
                     (FeedMessage         *message)
{
  static const FeedMessage init_value = FEED_MESSAGE__INIT;
  *message = init_value;
}
size_t feed_message__get_packed_size
                     (const FeedMessage *message)
{
  assert(message->base.descriptor == &feed_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t feed_message__pack
                     (const FeedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &feed_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t feed_message__pack_to_buffer
                     (const FeedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &feed_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FeedMessage *
       feed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FeedMessage *)
     protobuf_c_message_unpack (&feed_message__descriptor,
                                allocator, len, data);
}
void   feed_message__free_unpacked
                     (FeedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &feed_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   feed_header__init
                     (FeedHeader         *message)
{
  static const FeedHeader init_value = FEED_HEADER__INIT;
  *message = init_value;
}
size_t feed_header__get_packed_size
                     (const FeedHeader *message)
{
  assert(message->base.descriptor == &feed_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t feed_header__pack
                     (const FeedHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &feed_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t feed_header__pack_to_buffer
                     (const FeedHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &feed_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FeedHeader *
       feed_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FeedHeader *)
     protobuf_c_message_unpack (&feed_header__descriptor,
                                allocator, len, data);
}
void   feed_header__free_unpacked
                     (FeedHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &feed_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   feed_entity__init
                     (FeedEntity         *message)
{
  static const FeedEntity init_value = FEED_ENTITY__INIT;
  *message = init_value;
}
size_t feed_entity__get_packed_size
                     (const FeedEntity *message)
{
  assert(message->base.descriptor == &feed_entity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t feed_entity__pack
                     (const FeedEntity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &feed_entity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t feed_entity__pack_to_buffer
                     (const FeedEntity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &feed_entity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FeedEntity *
       feed_entity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FeedEntity *)
     protobuf_c_message_unpack (&feed_entity__descriptor,
                                allocator, len, data);
}
void   feed_entity__free_unpacked
                     (FeedEntity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &feed_entity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vehicle_position__carriage_details__init
                     (VehiclePosition__CarriageDetails         *message)
{
  static const VehiclePosition__CarriageDetails init_value = VEHICLE_POSITION__CARRIAGE_DETAILS__INIT;
  *message = init_value;
}
void   vehicle_position__init
                     (VehiclePosition         *message)
{
  static const VehiclePosition init_value = VEHICLE_POSITION__INIT;
  *message = init_value;
}
size_t vehicle_position__get_packed_size
                     (const VehiclePosition *message)
{
  assert(message->base.descriptor == &vehicle_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vehicle_position__pack
                     (const VehiclePosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vehicle_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vehicle_position__pack_to_buffer
                     (const VehiclePosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vehicle_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VehiclePosition *
       vehicle_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VehiclePosition *)
     protobuf_c_message_unpack (&vehicle_position__descriptor,
                                allocator, len, data);
}
void   vehicle_position__free_unpacked
                     (VehiclePosition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vehicle_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   position__init
                     (Position         *message)
{
  static const Position init_value = POSITION__INIT;
  *message = init_value;
}
size_t position__get_packed_size
                     (const Position *message)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t position__pack
                     (const Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t position__pack_to_buffer
                     (const Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Position *
       position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Position *)
     protobuf_c_message_unpack (&position__descriptor,
                                allocator, len, data);
}
void   position__free_unpacked
                     (Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trip_descriptor__modified_trip_selector__init
                     (TripDescriptor__ModifiedTripSelector         *message)
{
  static const TripDescriptor__ModifiedTripSelector init_value = TRIP_DESCRIPTOR__MODIFIED_TRIP_SELECTOR__INIT;
  *message = init_value;
}
void   trip_descriptor__init
                     (TripDescriptor         *message)
{
  static const TripDescriptor init_value = TRIP_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t trip_descriptor__get_packed_size
                     (const TripDescriptor *message)
{
  assert(message->base.descriptor == &trip_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trip_descriptor__pack
                     (const TripDescriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trip_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trip_descriptor__pack_to_buffer
                     (const TripDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trip_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TripDescriptor *
       trip_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TripDescriptor *)
     protobuf_c_message_unpack (&trip_descriptor__descriptor,
                                allocator, len, data);
}
void   trip_descriptor__free_unpacked
                     (TripDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trip_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vehicle_descriptor__init
                     (VehicleDescriptor         *message)
{
  static const VehicleDescriptor init_value = VEHICLE_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t vehicle_descriptor__get_packed_size
                     (const VehicleDescriptor *message)
{
  assert(message->base.descriptor == &vehicle_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vehicle_descriptor__pack
                     (const VehicleDescriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vehicle_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vehicle_descriptor__pack_to_buffer
                     (const VehicleDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vehicle_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VehicleDescriptor *
       vehicle_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VehicleDescriptor *)
     protobuf_c_message_unpack (&vehicle_descriptor__descriptor,
                                allocator, len, data);
}
void   vehicle_descriptor__free_unpacked
                     (VehicleDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vehicle_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor feed_message__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FeedMessage, header),
    &feed_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FeedMessage, n_entity),
    offsetof(FeedMessage, entity),
    &feed_entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned feed_message__field_indices_by_name[] = {
  1,   /* field[1] = entity */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange feed_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor feed_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FeedMessage",
  "FeedMessage",
  "FeedMessage",
  "",
  sizeof(FeedMessage),
  2,
  feed_message__field_descriptors,
  feed_message__field_indices_by_name,
  1,  feed_message__number_ranges,
  (ProtobufCMessageInit) feed_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue feed_header__incrementality__enum_values_by_number[2] =
{
  { "FULL_DATASET", "FEED_HEADER__INCREMENTALITY__FULL_DATASET", 0 },
  { "DIFFERENTIAL", "FEED_HEADER__INCREMENTALITY__DIFFERENTIAL", 1 },
};
static const ProtobufCIntRange feed_header__incrementality__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex feed_header__incrementality__enum_values_by_name[2] =
{
  { "DIFFERENTIAL", 1 },
  { "FULL_DATASET", 0 },
};
const ProtobufCEnumDescriptor feed_header__incrementality__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FeedHeader.Incrementality",
  "Incrementality",
  "FeedHeader__Incrementality",
  "",
  2,
  feed_header__incrementality__enum_values_by_number,
  2,
  feed_header__incrementality__enum_values_by_name,
  1,
  feed_header__incrementality__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const FeedHeader__Incrementality feed_header__incrementality__default_value = FEED_HEADER__INCREMENTALITY__FULL_DATASET;
static const ProtobufCFieldDescriptor feed_header__field_descriptors[4] =
{
  {
    "gtfs_realtime_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FeedHeader, gtfs_realtime_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incrementality",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(FeedHeader, has_incrementality),
    offsetof(FeedHeader, incrementality),
    &feed_header__incrementality__descriptor,
    &feed_header__incrementality__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(FeedHeader, has_timestamp),
    offsetof(FeedHeader, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feed_version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FeedHeader, feed_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned feed_header__field_indices_by_name[] = {
  3,   /* field[3] = feed_version */
  0,   /* field[0] = gtfs_realtime_version */
  1,   /* field[1] = incrementality */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange feed_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor feed_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FeedHeader",
  "FeedHeader",
  "FeedHeader",
  "",
  sizeof(FeedHeader),
  4,
  feed_header__field_descriptors,
  feed_header__field_indices_by_name,
  1,  feed_header__number_ranges,
  (ProtobufCMessageInit) feed_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean feed_entity__is_deleted__default_value = 0;
static const ProtobufCFieldDescriptor feed_entity__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FeedEntity, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_deleted",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(FeedEntity, has_is_deleted),
    offsetof(FeedEntity, is_deleted),
    NULL,
    &feed_entity__is_deleted__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FeedEntity, vehicle),
    &vehicle_position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned feed_entity__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = is_deleted */
  2,   /* field[2] = vehicle */
};
static const ProtobufCIntRange feed_entity__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor feed_entity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FeedEntity",
  "FeedEntity",
  "FeedEntity",
  "",
  sizeof(FeedEntity),
  3,
  feed_entity__field_descriptors,
  feed_entity__field_indices_by_name,
  2,  feed_entity__number_ranges,
  (ProtobufCMessageInit) feed_entity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const VehiclePosition__OccupancyStatus vehicle_position__carriage_details__occupancy_status__default_value = VEHICLE_POSITION__OCCUPANCY_STATUS__NO_DATA_AVAILABLE;
static const int32_t vehicle_position__carriage_details__occupancy_percentage__default_value = -1;
static const ProtobufCFieldDescriptor vehicle_position__carriage_details__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition__CarriageDetails, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition__CarriageDetails, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occupancy_status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VehiclePosition__CarriageDetails, has_occupancy_status),
    offsetof(VehiclePosition__CarriageDetails, occupancy_status),
    &vehicle_position__occupancy_status__descriptor,
    &vehicle_position__carriage_details__occupancy_status__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occupancy_percentage",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(VehiclePosition__CarriageDetails, has_occupancy_percentage),
    offsetof(VehiclePosition__CarriageDetails, occupancy_percentage),
    NULL,
    &vehicle_position__carriage_details__occupancy_percentage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carriage_sequence",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VehiclePosition__CarriageDetails, has_carriage_sequence),
    offsetof(VehiclePosition__CarriageDetails, carriage_sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vehicle_position__carriage_details__field_indices_by_name[] = {
  4,   /* field[4] = carriage_sequence */
  0,   /* field[0] = id */
  1,   /* field[1] = label */
  3,   /* field[3] = occupancy_percentage */
  2,   /* field[2] = occupancy_status */
};
static const ProtobufCIntRange vehicle_position__carriage_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor vehicle_position__carriage_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VehiclePosition.CarriageDetails",
  "CarriageDetails",
  "VehiclePosition__CarriageDetails",
  "",
  sizeof(VehiclePosition__CarriageDetails),
  5,
  vehicle_position__carriage_details__field_descriptors,
  vehicle_position__carriage_details__field_indices_by_name,
  1,  vehicle_position__carriage_details__number_ranges,
  (ProtobufCMessageInit) vehicle_position__carriage_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vehicle_position__vehicle_stop_status__enum_values_by_number[3] =
{
  { "INCOMING_AT", "VEHICLE_POSITION__VEHICLE_STOP_STATUS__INCOMING_AT", 0 },
  { "STOPPED_AT", "VEHICLE_POSITION__VEHICLE_STOP_STATUS__STOPPED_AT", 1 },
  { "IN_TRANSIT_TO", "VEHICLE_POSITION__VEHICLE_STOP_STATUS__IN_TRANSIT_TO", 2 },
};
static const ProtobufCIntRange vehicle_position__vehicle_stop_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex vehicle_position__vehicle_stop_status__enum_values_by_name[3] =
{
  { "INCOMING_AT", 0 },
  { "IN_TRANSIT_TO", 2 },
  { "STOPPED_AT", 1 },
};
const ProtobufCEnumDescriptor vehicle_position__vehicle_stop_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VehiclePosition.VehicleStopStatus",
  "VehicleStopStatus",
  "VehiclePosition__VehicleStopStatus",
  "",
  3,
  vehicle_position__vehicle_stop_status__enum_values_by_number,
  3,
  vehicle_position__vehicle_stop_status__enum_values_by_name,
  1,
  vehicle_position__vehicle_stop_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vehicle_position__congestion_level__enum_values_by_number[5] =
{
  { "UNKNOWN_CONGESTION_LEVEL", "VEHICLE_POSITION__CONGESTION_LEVEL__UNKNOWN_CONGESTION_LEVEL", 0 },
  { "RUNNING_SMOOTHLY", "VEHICLE_POSITION__CONGESTION_LEVEL__RUNNING_SMOOTHLY", 1 },
  { "STOP_AND_GO", "VEHICLE_POSITION__CONGESTION_LEVEL__STOP_AND_GO", 2 },
  { "CONGESTION", "VEHICLE_POSITION__CONGESTION_LEVEL__CONGESTION", 3 },
  { "SEVERE_CONGESTION", "VEHICLE_POSITION__CONGESTION_LEVEL__SEVERE_CONGESTION", 4 },
};
static const ProtobufCIntRange vehicle_position__congestion_level__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex vehicle_position__congestion_level__enum_values_by_name[5] =
{
  { "CONGESTION", 3 },
  { "RUNNING_SMOOTHLY", 1 },
  { "SEVERE_CONGESTION", 4 },
  { "STOP_AND_GO", 2 },
  { "UNKNOWN_CONGESTION_LEVEL", 0 },
};
const ProtobufCEnumDescriptor vehicle_position__congestion_level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VehiclePosition.CongestionLevel",
  "CongestionLevel",
  "VehiclePosition__CongestionLevel",
  "",
  5,
  vehicle_position__congestion_level__enum_values_by_number,
  5,
  vehicle_position__congestion_level__enum_values_by_name,
  1,
  vehicle_position__congestion_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vehicle_position__occupancy_status__enum_values_by_number[9] =
{
  { "EMPTY", "VEHICLE_POSITION__OCCUPANCY_STATUS__EMPTY", 0 },
  { "MANY_SEATS_AVAILABLE", "VEHICLE_POSITION__OCCUPANCY_STATUS__MANY_SEATS_AVAILABLE", 1 },
  { "FEW_SEATS_AVAILABLE", "VEHICLE_POSITION__OCCUPANCY_STATUS__FEW_SEATS_AVAILABLE", 2 },
  { "STANDING_ROOM_ONLY", "VEHICLE_POSITION__OCCUPANCY_STATUS__STANDING_ROOM_ONLY", 3 },
  { "CRUSHED_STANDING_ROOM_ONLY", "VEHICLE_POSITION__OCCUPANCY_STATUS__CRUSHED_STANDING_ROOM_ONLY", 4 },
  { "FULL", "VEHICLE_POSITION__OCCUPANCY_STATUS__FULL", 5 },
  { "NOT_ACCEPTING_PASSENGERS", "VEHICLE_POSITION__OCCUPANCY_STATUS__NOT_ACCEPTING_PASSENGERS", 6 },
  { "NO_DATA_AVAILABLE", "VEHICLE_POSITION__OCCUPANCY_STATUS__NO_DATA_AVAILABLE", 7 },
  { "NOT_BOARDABLE", "VEHICLE_POSITION__OCCUPANCY_STATUS__NOT_BOARDABLE", 8 },
};
static const ProtobufCIntRange vehicle_position__occupancy_status__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex vehicle_position__occupancy_status__enum_values_by_name[9] =
{
  { "CRUSHED_STANDING_ROOM_ONLY", 4 },
  { "EMPTY", 0 },
  { "FEW_SEATS_AVAILABLE", 2 },
  { "FULL", 5 },
  { "MANY_SEATS_AVAILABLE", 1 },
  { "NOT_ACCEPTING_PASSENGERS", 6 },
  { "NOT_BOARDABLE", 8 },
  { "NO_DATA_AVAILABLE", 7 },
  { "STANDING_ROOM_ONLY", 3 },
};
const ProtobufCEnumDescriptor vehicle_position__occupancy_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VehiclePosition.OccupancyStatus",
  "OccupancyStatus",
  "VehiclePosition__OccupancyStatus",
  "",
  9,
  vehicle_position__occupancy_status__enum_values_by_number,
  9,
  vehicle_position__occupancy_status__enum_values_by_name,
  1,
  vehicle_position__occupancy_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const VehiclePosition__VehicleStopStatus vehicle_position__current_status__default_value = VEHICLE_POSITION__VEHICLE_STOP_STATUS__IN_TRANSIT_TO;
static const ProtobufCFieldDescriptor vehicle_position__field_descriptors[11] =
{
  {
    "trip",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition, trip),
    &trip_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition, position),
    &position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_stop_sequence",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VehiclePosition, has_current_stop_sequence),
    offsetof(VehiclePosition, current_stop_sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_status",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VehiclePosition, has_current_status),
    offsetof(VehiclePosition, current_status),
    &vehicle_position__vehicle_stop_status__descriptor,
    &vehicle_position__current_status__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(VehiclePosition, has_timestamp),
    offsetof(VehiclePosition, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "congestion_level",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VehiclePosition, has_congestion_level),
    offsetof(VehiclePosition, congestion_level),
    &vehicle_position__congestion_level__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition, stop_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VehiclePosition, vehicle),
    &vehicle_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occupancy_status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VehiclePosition, has_occupancy_status),
    offsetof(VehiclePosition, occupancy_status),
    &vehicle_position__occupancy_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occupancy_percentage",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VehiclePosition, has_occupancy_percentage),
    offsetof(VehiclePosition, occupancy_percentage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multi_carriage_details",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VehiclePosition, n_multi_carriage_details),
    offsetof(VehiclePosition, multi_carriage_details),
    &vehicle_position__carriage_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vehicle_position__field_indices_by_name[] = {
  5,   /* field[5] = congestion_level */
  3,   /* field[3] = current_status */
  2,   /* field[2] = current_stop_sequence */
  10,   /* field[10] = multi_carriage_details */
  9,   /* field[9] = occupancy_percentage */
  8,   /* field[8] = occupancy_status */
  1,   /* field[1] = position */
  6,   /* field[6] = stop_id */
  4,   /* field[4] = timestamp */
  0,   /* field[0] = trip */
  7,   /* field[7] = vehicle */
};
static const ProtobufCIntRange vehicle_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor vehicle_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VehiclePosition",
  "VehiclePosition",
  "VehiclePosition",
  "",
  sizeof(VehiclePosition),
  11,
  vehicle_position__field_descriptors,
  vehicle_position__field_indices_by_name,
  1,  vehicle_position__number_ranges,
  (ProtobufCMessageInit) vehicle_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor position__field_descriptors[5] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Position, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Position, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bearing",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Position, has_bearing),
    offsetof(Position, bearing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "odometer",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Position, has_odometer),
    offsetof(Position, odometer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Position, has_speed),
    offsetof(Position, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned position__field_indices_by_name[] = {
  2,   /* field[2] = bearing */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = odometer */
  4,   /* field[4] = speed */
};
static const ProtobufCIntRange position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Position",
  "Position",
  "Position",
  "",
  sizeof(Position),
  5,
  position__field_descriptors,
  position__field_indices_by_name,
  1,  position__number_ranges,
  (ProtobufCMessageInit) position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trip_descriptor__modified_trip_selector__field_descriptors[4] =
{
  {
    "modifications_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor__ModifiedTripSelector, modifications_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "affected_trip_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor__ModifiedTripSelector, affected_trip_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor__ModifiedTripSelector, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_date",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor__ModifiedTripSelector, start_date),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trip_descriptor__modified_trip_selector__field_indices_by_name[] = {
  1,   /* field[1] = affected_trip_id */
  0,   /* field[0] = modifications_id */
  3,   /* field[3] = start_date */
  2,   /* field[2] = start_time */
};
static const ProtobufCIntRange trip_descriptor__modified_trip_selector__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor trip_descriptor__modified_trip_selector__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TripDescriptor.ModifiedTripSelector",
  "ModifiedTripSelector",
  "TripDescriptor__ModifiedTripSelector",
  "",
  sizeof(TripDescriptor__ModifiedTripSelector),
  4,
  trip_descriptor__modified_trip_selector__field_descriptors,
  trip_descriptor__modified_trip_selector__field_indices_by_name,
  1,  trip_descriptor__modified_trip_selector__number_ranges,
  (ProtobufCMessageInit) trip_descriptor__modified_trip_selector__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue trip_descriptor__schedule_relationship__enum_values_by_number[8] =
{
  { "SCHEDULED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__SCHEDULED", 0 },
  { "ADDED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__ADDED", 1 },
  { "UNSCHEDULED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__UNSCHEDULED", 2 },
  { "CANCELED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__CANCELED", 3 },
  { "REPLACEMENT", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__REPLACEMENT", 5 },
  { "DUPLICATED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__DUPLICATED", 6 },
  { "DELETED", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__DELETED", 7 },
  { "NEW", "TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__NEW", 8 },
};
static const ProtobufCIntRange trip_descriptor__schedule_relationship__value_ranges[] = {
{0, 0},{5, 4},{0, 8}
};
static const ProtobufCEnumValueIndex trip_descriptor__schedule_relationship__enum_values_by_name[8] =
{
  { "ADDED", 1 },
  { "CANCELED", 3 },
  { "DELETED", 6 },
  { "DUPLICATED", 5 },
  { "NEW", 7 },
  { "REPLACEMENT", 4 },
  { "SCHEDULED", 0 },
  { "UNSCHEDULED", 2 },
};
const ProtobufCEnumDescriptor trip_descriptor__schedule_relationship__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TripDescriptor.ScheduleRelationship",
  "ScheduleRelationship",
  "TripDescriptor__ScheduleRelationship",
  "",
  8,
  trip_descriptor__schedule_relationship__enum_values_by_number,
  8,
  trip_descriptor__schedule_relationship__enum_values_by_name,
  2,
  trip_descriptor__schedule_relationship__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor trip_descriptor__field_descriptors[7] =
{
  {
    "trip_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor, trip_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_date",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor, start_date),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedule_relationship",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TripDescriptor, has_schedule_relationship),
    offsetof(TripDescriptor, schedule_relationship),
    &trip_descriptor__schedule_relationship__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor, route_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TripDescriptor, has_direction_id),
    offsetof(TripDescriptor, direction_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modified_trip",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TripDescriptor, modified_trip),
    &trip_descriptor__modified_trip_selector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trip_descriptor__field_indices_by_name[] = {
  5,   /* field[5] = direction_id */
  6,   /* field[6] = modified_trip */
  4,   /* field[4] = route_id */
  3,   /* field[3] = schedule_relationship */
  2,   /* field[2] = start_date */
  1,   /* field[1] = start_time */
  0,   /* field[0] = trip_id */
};
static const ProtobufCIntRange trip_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor trip_descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TripDescriptor",
  "TripDescriptor",
  "TripDescriptor",
  "",
  sizeof(TripDescriptor),
  7,
  trip_descriptor__field_descriptors,
  trip_descriptor__field_indices_by_name,
  1,  trip_descriptor__number_ranges,
  (ProtobufCMessageInit) trip_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vehicle_descriptor__wheelchair_accessible__enum_values_by_number[4] =
{
  { "NO_VALUE", "VEHICLE_DESCRIPTOR__WHEELCHAIR_ACCESSIBLE__NO_VALUE", 0 },
  { "UNKNOWN", "VEHICLE_DESCRIPTOR__WHEELCHAIR_ACCESSIBLE__UNKNOWN", 1 },
  { "WHEELCHAIR_ACCESSIBLE", "VEHICLE_DESCRIPTOR__WHEELCHAIR_ACCESSIBLE__WHEELCHAIR_ACCESSIBLE", 2 },
  { "WHEELCHAIR_INACCESSIBLE", "VEHICLE_DESCRIPTOR__WHEELCHAIR_ACCESSIBLE__WHEELCHAIR_INACCESSIBLE", 3 },
};
static const ProtobufCIntRange vehicle_descriptor__wheelchair_accessible__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex vehicle_descriptor__wheelchair_accessible__enum_values_by_name[4] =
{
  { "NO_VALUE", 0 },
  { "UNKNOWN", 1 },
  { "WHEELCHAIR_ACCESSIBLE", 2 },
  { "WHEELCHAIR_INACCESSIBLE", 3 },
};
const ProtobufCEnumDescriptor vehicle_descriptor__wheelchair_accessible__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VehicleDescriptor.WheelchairAccessible",
  "WheelchairAccessible",
  "VehicleDescriptor__WheelchairAccessible",
  "",
  4,
  vehicle_descriptor__wheelchair_accessible__enum_values_by_number,
  4,
  vehicle_descriptor__wheelchair_accessible__enum_values_by_name,
  1,
  vehicle_descriptor__wheelchair_accessible__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const VehicleDescriptor__WheelchairAccessible vehicle_descriptor__wheelchair_accessible__default_value = VEHICLE_DESCRIPTOR__WHEELCHAIR_ACCESSIBLE__NO_VALUE;
static const ProtobufCFieldDescriptor vehicle_descriptor__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehicleDescriptor, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehicleDescriptor, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "license_plate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VehicleDescriptor, license_plate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wheelchair_accessible",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VehicleDescriptor, has_wheelchair_accessible),
    offsetof(VehicleDescriptor, wheelchair_accessible),
    &vehicle_descriptor__wheelchair_accessible__descriptor,
    &vehicle_descriptor__wheelchair_accessible__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vehicle_descriptor__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = label */
  2,   /* field[2] = license_plate */
  3,   /* field[3] = wheelchair_accessible */
};
static const ProtobufCIntRange vehicle_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vehicle_descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VehicleDescriptor",
  "VehicleDescriptor",
  "VehicleDescriptor",
  "",
  sizeof(VehicleDescriptor),
  4,
  vehicle_descriptor__field_descriptors,
  vehicle_descriptor__field_indices_by_name,
  1,  vehicle_descriptor__number_ranges,
  (ProtobufCMessageInit) vehicle_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
